-- Replaced 30 Political Parties 
INSERT INTO parties (name_en, name_np, abbreviation, color_hex, symbol_cloudinary_url) VALUES
('Nepali Congress', 'नेपाली काँग्रेस', 'NC', '#0047AB', 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Nepali_Congress_alt_flag.svg'),
('Communist Party of Nepal (Unified Marxist–Leninist)', 'नेकपा (एकीकृत मार्क्सवादी-लेनिनवादी)', 'UML', '#E10600', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/CPN-UML_Flag.svg'),
('Rastriya Swatantra Party', 'राष्ट्रिय स्वतन्त्र पार्टी', 'RSP', '#FF6B00', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Rastriya_Swatantra_Party_logo.png/200px-Rastriya_Swatantra_Party_logo.png'),
('Nepali Communist Party (2025 merger)', 'नेपाली कम्युनिस्ट पार्टी', 'NCP', '#CC0000', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Flag_of_CPN_%28Maoist_Centre%29.svg/200px-Flag_of_CPN_%28Maoist_Centre%29.svg.png'),
('Rastriya Prajatantra Party', 'राष्ट्रिय प्रजातन्त्र पार्टी', 'RPP', '#006400', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Rastriya_Prajatantra_Party_Nepal_logo.png/200px-Rastriya_Prajatantra_Party_Nepal_logo.png'),
('People''s Socialist Party Nepal (Janata Samajwadi Party-Nepal)', 'जनता समाजवादी पार्टी नेपाल', 'PSP-N', '#8B4513', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Janata_Samajbadi_Party_Nepal_Flag.svg/200px-Janata_Samajbadi_Party_Nepal_Flag.svg.png'),
('Janamat Party', 'जनमत पार्टी', 'Janamat', '#DAA520', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Janamat_party_logo.png/200px-Janamat_party_logo.png'),
('Ujyaalo Nepal Party', 'उज्यालो नेपाल पार्टी', 'UNP', '#FFD700', NULL),
('Shram Sanskriti Party', 'श्रम संस्कृति पार्टी', 'SSP', '#8B0000', NULL),
('Aam Janata Party', 'आम जनता पार्टी', 'AJP', '#4B0082', NULL),
('Nepal Workers and Peasants Party', 'नेपाल मजदुर किसान पार्टी', 'NWPP', '#B22222', NULL),
('Mongol National Organization', 'मंगोल राष्ट्रिय संगठन', 'MNO', '#556B2F', NULL),
('Rastriya Mukti Party Nepal', 'राष्ट्रिय मुक्ति पार्टी नेपाल', 'RMP', '#708090', NULL),
('Pragatishil Loktantrik Party', 'प्रगतिशील लोकतान्त्रिक पार्टी', 'PLP', '#2E8B57', NULL),
('Sanghiya Loktantrik Rastriya Manch', 'संघीय लोकतान्त्रिक राष्ट्रिय मञ्च', 'SLRM', '#CD853F', NULL),
('Nepal Janamukti Party', 'नेपाल जनमुक्ति पार्टी', 'NJP', '#4169E1', NULL),
('Rastriya Pariwartan Party', 'राष्ट्रिय परिवर्तन पार्टी', 'RPaP', '#FF8C00', NULL),
('Rastriya Janamukti Party', 'राष्ट्रिय जनमुक्ति पार्टी', 'RJP', '#9400D3', NULL),
('Nepal Communist Party (Sainyukta)', 'नेपाल कम्युनिस्ट पार्टी (संयुक्त)', 'NCPSa', '#DC143C', NULL),
('Nepal Communist Party Marxist (Pushpalal)', 'नेपाल कम्युनिस्ट पार्टी मार्क्सवादी (पुष्पलाल)', 'NCPMarx', '#8B0000', NULL),
('National Republic Nepal', 'राष्ट्रिय गणतन्त्र नेपाल', 'NatRepNepal', '#2F4F4F', NULL),
('Rastriya Janamorcha', 'राष्ट्रिय जनमोर्चा', 'RJanaMorcha', '#A52A2A', NULL),
('Nepali Janashramdan Sanskriti Party', 'नेपाली जनश्रमदान संस्कृति पार्टी', 'NJSSP', '#696969', NULL),
('Nagarik Unmukti Party', 'नागरिक उन्मुक्ति पार्टी', 'NUP', '#20B2AA', NULL),
('People First Party', 'जनता पहिले पार्टी', 'PFP', '#FF69B4', NULL),
('Nepal Federal Socialist Party', 'नेपाल संघीय समाजवादी पार्टी', 'NFSP', '#6B8E23', NULL),
('Rastriya Mukti Party (Single Symbol)', 'राष्ट्रिय मुक्ति पार्टी (एकल चुनाव चिन्ह)', 'Mukti', '#708090', NULL),
('Janajati Party / Janajati front parties', 'जनजाति पार्टी', 'JP', '#228B22', NULL),
('Swatantra Party (various)', 'स्वतन्त्र पार्टी', 'SwaP', '#C0C0C0', NULL),
('Independent', 'स्वतन्त्र', 'IND', '#6B7280', NULL);
