TRUNCATE TABLE provinces, districts, constituencies, parties, candidates, results, vote_snapshots, scrape_log RESTART IDENTITY CASCADE;

-- Insert Provinces
INSERT INTO provinces (id, name_en, name_np) VALUES
(1, 'Koshi', 'कोशी'),
(2, 'Madhesh', 'मधेश'),
(3, 'Bagmati', 'बागमती'),
(4, 'Gandaki', 'गण्डकी'),
(5, 'Lumbini', 'लुम्बिनी'),
(6, 'Karnali', 'कर्णाली'),
(7, 'Sudurpashchim', 'सुदूरपश्चिम')
ON CONFLICT (id) DO NOTHING;

-- Replaced 30 Political Parties 
INSERT INTO parties (name_en, name_np, abbreviation, color_hex, symbol_cloudinary_url) VALUES
('Nepali Congress', 'नेपाली काँग्रेस', 'NC', '#0047AB', 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Nepali_Congress_alt_flag.svg'),
('Communist Party of Nepal (Unified Marxist–Leninist)', 'नेकपा (एकीकृत मार्क्सवादी-लेनिनवादी)', 'UML', '#E10600', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/CPN-UML_Flag.svg'),
('Rastriya Swatantra Party', 'राष्ट्रिय स्वतन्त्र पार्टी', 'RSP', '#FF6B00', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Rastriya_Swatantra_Party_logo.png/200px-Rastriya_Swatantra_Party_logo.png'),
('Nepali Communist Party (2025 merger)', 'नेपाली कम्युनिस्ट पार्टी', 'NCP', '#CC0000', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Flag_of_CPN_%28Maoist_Centre%29.svg/200px-Flag_of_CPN_%28Maoist_Centre%29.svg.png'),
('Rastriya Prajatantra Party', 'राष्ट्रिय प्रजातन्त्र पार्टी', 'RPP', '#006400', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Rastriya_Prajatantra_Party_Nepal_logo.png/200px-Rastriya_Prajatantra_Party_Nepal_logo.png'),
('People''s Socialist Party Nepal (Janata Samajwadi Party-Nepal)', 'जनता समाजवादी पार्टी नेपाल', 'PSP-N', '#8B4513', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Janata_Samajbadi_Party_Nepal_Flag.svg/200px-Janata_Samajbadi_Party_Nepal_Flag.svg.png'),
('Janamat Party', 'जनमत पार्टी', 'Janamat', '#DAA520', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Janamat_party_logo.png/200px-Janamat_party_logo.png'),
('Ujyaalo Nepal Party', 'उज्यालो नेपाल पार्टी', 'UNP', '#FFD700', NULL),
('Shram Sanskriti Party', 'श्रम संस्कृति पार्टी', 'SSP', '#8B0000', NULL),
('Aam Janata Party', 'आम जनता पार्टी', 'AJP', '#4B0082', NULL),
('Nepal Workers and Peasants Party', 'नेपाल मजदुर किसान पार्टी', 'NWPP', '#B22222', NULL),
('Mongol National Organization', 'मंगोल राष्ट्रिय संगठन', 'MNO', '#556B2F', NULL),
('Rastriya Mukti Party Nepal', 'राष्ट्रिय मुक्ति पार्टी नेपाल', 'RMP', '#708090', NULL),
('Pragatishil Loktantrik Party', 'प्रगतिशील लोकतान्त्रिक पार्टी', 'PLP', '#2E8B57', NULL),
('Sanghiya Loktantrik Rastriya Manch', 'संघीय लोकतान्त्रिक राष्ट्रिय मञ्च', 'SLRM', '#CD853F', NULL),
('Nepal Janamukti Party', 'नेपाल जनमुक्ति पार्टी', 'NJP', '#4169E1', NULL),
('Rastriya Pariwartan Party', 'राष्ट्रिय परिवर्तन पार्टी', 'RPaP', '#FF8C00', NULL),
('Rastriya Janamukti Party', 'राष्ट्रिय जनमुक्ति पार्टी', 'RJP', '#9400D3', NULL),
('Nepal Communist Party (Sainyukta)', 'नेपाल कम्युनिस्ट पार्टी (संयुक्त)', 'NCPSa', '#DC143C', NULL),
('Nepal Communist Party Marxist (Pushpalal)', 'नेपाल कम्युनिस्ट पार्टी मार्क्सवादी (पुष्पलाल)', 'NCPMarx', '#8B0000', NULL),
('National Republic Nepal', 'राष्ट्रिय गणतन्त्र नेपाल', 'NatRepNepal', '#2F4F4F', NULL),
('Rastriya Janamorcha', 'राष्ट्रिय जनमोर्चा', 'RJanaMorcha', '#A52A2A', NULL),
('Nepali Janashramdan Sanskriti Party', 'नेपाली जनश्रमदान संस्कृति पार्टी', 'NJSSP', '#696969', NULL),
('Nagarik Unmukti Party', 'नागरिक उन्मुक्ति पार्टी', 'NUP', '#20B2AA', NULL),
('People First Party', 'जनता पहिले पार्टी', 'PFP', '#FF69B4', NULL),
('Nepal Federal Socialist Party', 'नेपाल संघीय समाजवादी पार्टी', 'NFSP', '#6B8E23', NULL),
('Rastriya Mukti Party (Single Symbol)', 'राष्ट्रिय मुक्ति पार्टी (एकल चुनाव चिन्ह)', 'Mukti', '#708090', NULL),
('Janajati Party / Janajati front parties', 'जनजाति पार्टी', 'JP', '#228B22', NULL),
('Swatantra Party (various)', 'स्वतन्त्र पार्टी', 'SwaP', '#C0C0C0', NULL),
('Independent', 'स्वतन्त्र', 'IND', '#6B7280', NULL);
-- 77 Districts
INSERT INTO districts (province_id, name_en, name_np) VALUES
-- 1. Koshi Province (14)
(1, 'Bhojpur', 'भोजपुर'),
(1, 'Dhankuta', 'धनकुटा'),
(1, 'Ilam', 'इलाम'),
(1, 'Jhapa', 'झापा'),
(1, 'Khotang', 'खोटाङ'),
(1, 'Morang', 'मोरङ'),
(1, 'Okhaldhunga', 'ओखलढुङ्गा'),
(1, 'Panchthar', 'पाँचथर'),
(1, 'Sankhuwasabha', 'संखुवासभा'),
(1, 'Solukhumbu', 'सोलुखुम्बु'),
(1, 'Sunsari', 'सुनसरी'),
(1, 'Taplejung', 'ताप्लेजुङ'),
(1, 'Tehrathum', 'तेह्रथुम'),
(1, 'Udayapur', 'उदयपुर'),

-- 2. Madhesh Province (8)
(2, 'Bara', 'बारा'),
(2, 'Dhanusha', 'धनुषा'),
(2, 'Mahottari', 'महोत्तरी'),
(2, 'Parsa', 'पर्सा'),
(2, 'Rautahat', 'रौतहट'),
(2, 'Saptari', 'सप्तरी'),
(2, 'Sarlahi', 'सर्लाही'),
(2, 'Siraha', 'सिराहा'),

-- 3. Bagmati Province (13)
(3, 'Bhaktapur', 'भक्तपुर'),
(3, 'Chitwan', 'चितवन'),
(3, 'Dhading', 'धादिङ'),
(3, 'Dolakha', 'दोलखा'),
(3, 'Kathmandu', 'काठमाडौँ'),
(3, 'Kavrepalanchok', 'काभ्रेपलाञ्चोक'),
(3, 'Lalitpur', 'ललितपुर'),
(3, 'Makwanpur', 'मकवानपुर'),
(3, 'Nuwakot', 'नुवाकोट'),
(3, 'Ramechhap', 'रामेछाप'),
(3, 'Rasuwa', 'रसुवा'),
(3, 'Sindhuli', 'सिन्धुली'),
(3, 'Sindhupalchok', 'सिन्धुपाल्चोक'),

-- 4. Gandaki Province (11)
(4, 'Baglung', 'बागलुङ'),
(4, 'Gorkha', 'गोरखा'),
(4, 'Kaski', 'कास्की'),
(4, 'Lamjung', 'लमजुङ'),
(4, 'Manang', 'मनाङ'),
(4, 'Mustang', 'मुस्ताङ'),
(4, 'Myagdi', 'म्याग्दी'),
(4, 'Nawalpur', 'नवलपुर'),
(4, 'Parbat', 'पर्वत'),
(4, 'Syangja', 'स्याङ्जा'),
(4, 'Tanahun', 'तनहुँ'),

-- 5. Lumbini Province (12)
(5, 'Arghakhanchi', 'अर्घाखाँची'),
(5, 'Banke', 'बाँके'),
(5, 'Bardiya', 'बर्दिया'),
(5, 'Dang', 'दाङ'),
(5, 'Eastern Rukum', 'पूर्वी रुकुम'),
(5, 'Gulmi', 'गुल्मी'),
(5, 'Kapilvastu', 'कपिलवस्तु'),
(5, 'Parasi', 'परासी'),
(5, 'Palpa', 'पाल्पा'),
(5, 'Pyuthan', 'प्युठान'),
(5, 'Rolpa', 'रोल्पा'),
(5, 'Rupandehi', 'रुपन्देही'),

-- 6. Karnali Province (10)
(6, 'Dailekh', 'दैलेख'),
(6, 'Dolpa', 'डोल्पा'),
(6, 'Humla', 'हुम्ला'),
(6, 'Jajarkot', 'जाजरकोट'),
(6, 'Jumla', 'जुम्ला'),
(6, 'Kalikot', 'कालिकोट'),
(6, 'Mugu', 'मुगु'),
(6, 'Salyan', 'सल्यान'),
(6, 'Surkhet', 'सुर्खेत'),
(6, 'Western Rukum', 'पश्चिम रुकुम'),

-- 7. Sudurpashchim Province (9)
(7, 'Achham', 'अछाम'),
(7, 'Baitadi', 'बैतडी'),
(7, 'Bajhang', 'बझाङ'),
(7, 'Bajura', 'बाजुरा'),
(7, 'Dadeldhura', 'डडेलधुरा'),
(7, 'Darchula', 'दार्चुला'),
(7, 'Doti', 'डोटी'),
(7, 'Kailali', 'कैलाली'),
(7, 'Kanchanpur', 'कञ्चनपुर');

-- All 165 Constituencies
INSERT INTO constituencies (district_id, number, name_en, name_np) VALUES
(1, 1, 'Bhojpur-1', NULL),
(2, 1, 'Dhankuta-1', NULL),
(3, 1, 'Ilam-1', NULL),
(3, 2, 'Ilam-2', NULL),
(4, 1, 'Jhapa-1', NULL),
(4, 2, 'Jhapa-2', NULL),
(4, 3, 'Jhapa-3', NULL),
(4, 4, 'Jhapa-4', NULL),
(4, 5, 'Jhapa-5', NULL),
(5, 1, 'Khotang-1', NULL),
(6, 1, 'Morang-1', NULL),
(6, 2, 'Morang-2', NULL),
(6, 3, 'Morang-3', NULL),
(6, 4, 'Morang-4', NULL),
(6, 5, 'Morang-5', NULL),
(6, 6, 'Morang-6', NULL),
(7, 1, 'Okhaldhunga-1', NULL),
(8, 1, 'Panchthar-1', NULL),
(9, 1, 'Sankhuwasabha-1', NULL),
(10, 1, 'Solukhumbu-1', NULL),
(11, 1, 'Sunsari-1', NULL),
(11, 2, 'Sunsari-2', NULL),
(11, 3, 'Sunsari-3', NULL),
(11, 4, 'Sunsari-4', NULL),
(12, 1, 'Taplejung-1', NULL),
(13, 1, 'Tehrathum-1', NULL),
(14, 1, 'Udayapur-1', NULL),
(14, 2, 'Udayapur-2', NULL),
(15, 1, 'Bara-1', NULL),
(15, 2, 'Bara-2', NULL),
(15, 3, 'Bara-3', NULL),
(15, 4, 'Bara-4', NULL),
(16, 1, 'Dhanusha-1', NULL),
(16, 2, 'Dhanusha-2', NULL),
(16, 3, 'Dhanusha-3', NULL),
(16, 4, 'Dhanusha-4', NULL),
(17, 1, 'Mahottari-1', NULL),
(17, 2, 'Mahottari-2', NULL),
(17, 3, 'Mahottari-3', NULL),
(17, 4, 'Mahottari-4', NULL),
(18, 1, 'Parsa-1', NULL),
(18, 2, 'Parsa-2', NULL),
(18, 3, 'Parsa-3', NULL),
(18, 4, 'Parsa-4', NULL),
(19, 1, 'Rautahat-1', NULL),
(19, 2, 'Rautahat-2', NULL),
(19, 3, 'Rautahat-3', NULL),
(19, 4, 'Rautahat-4', NULL),
(20, 1, 'Saptari-1', NULL),
(20, 2, 'Saptari-2', NULL),
(20, 3, 'Saptari-3', NULL),
(20, 4, 'Saptari-4', NULL),
(21, 1, 'Sarlahi-1', NULL),
(21, 2, 'Sarlahi-2', NULL),
(21, 3, 'Sarlahi-3', NULL),
(21, 4, 'Sarlahi-4', NULL),
(22, 1, 'Siraha-1', NULL),
(22, 2, 'Siraha-2', NULL),
(22, 3, 'Siraha-3', NULL),
(22, 4, 'Siraha-4', NULL),
(23, 1, 'Bhaktapur-1', NULL),
(23, 2, 'Bhaktapur-2', NULL),
(24, 1, 'Chitwan-1', NULL),
(24, 2, 'Chitwan-2', NULL),
(24, 3, 'Chitwan-3', NULL),
(25, 1, 'Dhading-1', NULL),
(25, 2, 'Dhading-2', NULL),
(26, 1, 'Dolakha-1', NULL),
(27, 1, 'Kathmandu-1', NULL),
(27, 2, 'Kathmandu-2', NULL),
(27, 3, 'Kathmandu-3', NULL),
(27, 4, 'Kathmandu-4', NULL),
(27, 5, 'Kathmandu-5', NULL),
(27, 6, 'Kathmandu-6', NULL),
(27, 7, 'Kathmandu-7', NULL),
(27, 8, 'Kathmandu-8', NULL),
(27, 9, 'Kathmandu-9', NULL),
(27, 10, 'Kathmandu-10', NULL),
(28, 1, 'Kavrepalanchok-1', NULL),
(28, 2, 'Kavrepalanchok-2', NULL),
(29, 1, 'Lalitpur-1', NULL),
(29, 2, 'Lalitpur-2', NULL),
(29, 3, 'Lalitpur-3', NULL),
(30, 1, 'Makwanpur-1', NULL),
(30, 2, 'Makwanpur-2', NULL),
(31, 1, 'Nuwakot-1', NULL),
(31, 2, 'Nuwakot-2', NULL),
(32, 1, 'Ramechhap-1', NULL),
(33, 1, 'Rasuwa-1', NULL),
(34, 1, 'Sindhuli-1', NULL),
(34, 2, 'Sindhuli-2', NULL),
(35, 1, 'Sindhupalchok-1', NULL),
(35, 2, 'Sindhupalchok-2', NULL),
(36, 1, 'Baglung-1', NULL),
(36, 2, 'Baglung-2', NULL),
(37, 1, 'Gorkha-1', NULL),
(37, 2, 'Gorkha-2', NULL),
(38, 1, 'Kaski-1', NULL),
(38, 2, 'Kaski-2', NULL),
(38, 3, 'Kaski-3', NULL),
(39, 1, 'Lamjung-1', NULL),
(40, 1, 'Manang-1', NULL),
(41, 1, 'Mustang-1', NULL),
(42, 1, 'Myagdi-1', NULL),
(43, 1, 'Nawalpur-1', NULL),
(43, 2, 'Nawalpur-2', NULL),
(44, 1, 'Parbat-1', NULL),
(45, 1, 'Syangja-1', NULL),
(45, 2, 'Syangja-2', NULL),
(46, 1, 'Tanahun-1', NULL),
(46, 2, 'Tanahun-2', NULL),
(47, 1, 'Arghakhanchi-1', NULL),
(48, 1, 'Banke-1', NULL),
(48, 2, 'Banke-2', NULL),
(48, 3, 'Banke-3', NULL),
(49, 1, 'Bardiya-1', NULL),
(49, 2, 'Bardiya-2', NULL),
(50, 1, 'Dang-1', NULL),
(50, 2, 'Dang-2', NULL),
(50, 3, 'Dang-3', NULL),
(51, 1, 'Eastern Rukum-1', NULL),
(52, 1, 'Gulmi-1', NULL),
(52, 2, 'Gulmi-2', NULL),
(53, 1, 'Kapilvastu-1', NULL),
(53, 2, 'Kapilvastu-2', NULL),
(53, 3, 'Kapilvastu-3', NULL),
(54, 1, 'Parasi-1', NULL),
(54, 2, 'Parasi-2', NULL),
(55, 1, 'Palpa-1', NULL),
(55, 2, 'Palpa-2', NULL),
(56, 1, 'Pyuthan-1', NULL),
(57, 1, 'Rolpa-1', NULL),
(58, 1, 'Rupandehi-1', NULL),
(58, 2, 'Rupandehi-2', NULL),
(58, 3, 'Rupandehi-3', NULL),
(58, 4, 'Rupandehi-4', NULL),
(58, 5, 'Rupandehi-5', NULL),
(59, 1, 'Dailekh-1', NULL),
(59, 2, 'Dailekh-2', NULL),
(60, 1, 'Dolpa-1', NULL),
(61, 1, 'Humla-1', NULL),
(62, 1, 'Jajarkot-1', NULL),
(63, 1, 'Jumla-1', NULL),
(64, 1, 'Kalikot-1', NULL),
(65, 1, 'Mugu-1', NULL),
(66, 1, 'Salyan-1', NULL),
(67, 1, 'Surkhet-1', NULL),
(67, 2, 'Surkhet-2', NULL),
(68, 1, 'Western Rukum-1', NULL),
(69, 1, 'Achham-1', NULL),
(69, 2, 'Achham-2', NULL),
(70, 1, 'Baitadi-1', NULL),
(71, 1, 'Bajhang-1', NULL),
(72, 1, 'Bajura-1', NULL),
(73, 1, 'Dadeldhura-1', NULL),
(74, 1, 'Darchula-1', NULL),
(75, 1, 'Doti-1', NULL),
(76, 1, 'Kailali-1', NULL),
(76, 2, 'Kailali-2', NULL),
(76, 3, 'Kailali-3', NULL),
(76, 4, 'Kailali-4', NULL),
(76, 5, 'Kailali-5', NULL),
(77, 1, 'Kanchanpur-1', NULL),
(77, 2, 'Kanchanpur-2', NULL),
(77, 3, 'Kanchanpur-3', NULL);

-- Update Party Symbols with placeholder URLs

-- Adding mock candidates for Kathmandu-1 (id: 91)
INSERT INTO candidates (constituency_id, party_id, is_independent, name_en, name_np, photo_cloudinary_url, ecn_candidate_id) VALUES
(91, 1, false, 'Prakash Man Singh', 'प्रकाशमान सिंह', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Prakash_Man_Singh.jpg/220px-Prakash_Man_Singh.jpg', 'KTM1_NC_01'),
(91, 3, false, 'Pukar Bam', 'पुकार बम', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Face-placeholder.svg', 'KTM1_RSP_01'),
(91, 2, false, 'Kiran Poudel', 'किरण पौडेल', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Face-placeholder.svg', 'KTM1_UML_01'),
(91, 5, false, 'Rabindra Mishra', 'रवीन्द्र मिश्र', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Rabindra_Mishra.jpg/220px-Rabindra_Mishra.jpg', 'KTM1_RPP_01');

-- Adding mock candidates for Sunsari-1 (id: 21)
INSERT INTO candidates (constituency_id, party_id, is_independent, name_en, name_np, photo_cloudinary_url, ecn_candidate_id) VALUES
(21, 3, false, 'Goma Tamang', 'गोमा तामाङ', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Face-placeholder.svg', 'SUN1_RSP_01'),
(21, 1, false, 'Jay Kumar Rai', 'जय कुमार राई', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Face-placeholder.svg', 'SUN1_NC_01'),
(21, 2, false, 'Ashok Kumar Rai', 'अशोक कुमार राई', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Face-placeholder.svg', 'SUN1_UML_01');

-- Insert initial empty Results for Kathmandu-1
INSERT INTO results (candidate_id, constituency_id, votes, is_winner) VALUES
((SELECT id FROM candidates WHERE ecn_candidate_id = 'KTM1_NC_01'), 91, 0, false),
((SELECT id FROM candidates WHERE ecn_candidate_id = 'KTM1_RSP_01'), 91, 0, false),
((SELECT id FROM candidates WHERE ecn_candidate_id = 'KTM1_UML_01'), 91, 0, false),
((SELECT id FROM candidates WHERE ecn_candidate_id = 'KTM1_RPP_01'), 91, 0, false);

-- Insert initial empty Results for Sunsari-1
INSERT INTO results (candidate_id, constituency_id, votes, is_winner) VALUES
((SELECT id FROM candidates WHERE ecn_candidate_id = 'SUN1_RSP_01'), 21, 0, false),
((SELECT id FROM candidates WHERE ecn_candidate_id = 'SUN1_NC_01'), 21, 0, false),
((SELECT id FROM candidates WHERE ecn_candidate_id = 'SUN1_UML_01'), 21, 0, false);
